apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec: 
  acme:
    server: https://acme-v02.api.letencrypt.org/directory
    email: 'handzelewicz@gmail.com'
    privateKeySecretRef: 
      name: letsencrypt-prod
    http01: {}